package flann;

public class FlannAlgorithmType {
	public static final int FLANN_INDEX_LINEAR = 0, FLANN_INDEX_KDTREE = 1,
			FLANN_INDEX_KMEANS = 2, FLANN_INDEX_COMPOSITE = 3,
			FLANN_INDEX_KDTREE_SINGLE = 4, FLANN_INDEX_HIERARCHICAL = 5,
			FLANN_INDEX_LSH = 6, FLANN_INDEX_KDTREE_CUDA = 7,
			FLANN_INDEX_SAVED = 254, FLANN_INDEX_AUTOTUNED = 255;

}
