package flann;

public class FlannDistanceType {
	public static final int FLANN_DIST_EUCLIDEAN = 1, FLANN_DIST_L2 = 1,
			FLANN_DIST_MANHATTAN = 2, FLANN_DIST_L1 = 2,
			FLANN_DIST_MINKOWSKI = 3, FLANN_DIST_MAX = 4,
			FLANN_DIST_HIST_INTERSECT = 5, FLANN_DIST_HELLINGER = 6,
			FLANN_DIST_CHI_SQUARE = 7, FLANN_DIST_KULLBACK_LEIBLER = 8,
			FLANN_DIST_HAMMING = 9, FLANN_DIST_HAMMING_LUT = 10,
			FLANN_DIST_HAMMING_POPCNT = 11, FLANN_DIST_L2_SIMPLE = 12;
}
